-- MySQL Script generated by MySQL Workbench
-- 07/18/16 21:57:05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema INFO5051_Books
-- -----------------------------------------------------
-- Script to generate the INFO5051 Books Database and its tables.
DROP SCHEMA IF EXISTS `INFO5051_Books` ;

-- -----------------------------------------------------
-- Schema INFO5051_Books
--
-- Script to generate the INFO5051 Books Database and its tables.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `INFO5051_Books` DEFAULT CHARACTER SET utf8 ;
USE `INFO5051_Books` ;

-- -----------------------------------------------------
-- Table `Book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Book` ;

CREATE TABLE IF NOT EXISTS `Book` (
  `BookID` INT NOT NULL AUTO_INCREMENT COMMENT 'Auto incremented BOOK_id number',
  `Title` VARCHAR(255) NULL COMMENT 'Full title of the book',
  `ISBN` VARCHAR(20) NULL COMMENT 'ISBN number of the book, either ISBN 10 or ISBN 13 is acceptable',
  `Edition_Number` VARCHAR(3) NULL COMMENT 'edtion number of the book',
  `Subject` VARCHAR(45) NULL COMMENT 'Subject of the book, ie programming language',
  `Available` INT NULL DEFAULT 1 COMMENT 'Using as a boolean field. Value of 0 means book is out, any other value book is available',
  PRIMARY KEY (`BookID`))
ENGINE = InnoDB
COMMENT = 'junction table between Book and Author\n';

CREATE UNIQUE INDEX `BookID_UNIQUE` ON `Book` (`BookID` ASC);


-- -----------------------------------------------------
-- Table `Author`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Author` ;

CREATE TABLE IF NOT EXISTS `Author` (
  `AuthorID` INT NOT NULL AUTO_INCREMENT,
  `Last_Name` VARCHAR(45) NULL,
  `First_name` VARCHAR(45) NULL,
  PRIMARY KEY (`AuthorID`))
ENGINE = InnoDB;

CREATE INDEX `BookID` ON `Author` (`AuthorID` ASC);


-- -----------------------------------------------------
-- Table `Book_Author`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Book_Author` ;

CREATE TABLE IF NOT EXISTS `Book_Author` (
  `Book_BookID` INT NOT NULL,
  `Author_AuthorID` INT NOT NULL,
  CONSTRAINT `fk_Book_Author_Book1`
    FOREIGN KEY (`Book_BookID`)
    REFERENCES `Book` (`BookID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Book_Author_Author1`
    FOREIGN KEY (`Author_AuthorID`)
    REFERENCES `Author` (`AuthorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'junction table between Book and Author tables\n';

CREATE INDEX `fk_Book_Author_Book1_idx` ON `Book_Author` (`Book_BookID` ASC);

CREATE INDEX `fk_Book_Author_Author1_idx` ON `Book_Author` (`Author_AuthorID` ASC);


-- -----------------------------------------------------
-- Table `Borrower`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Borrower` ;

CREATE TABLE IF NOT EXISTS `Borrower` (
  `Borrower_ID` INT NOT NULL AUTO_INCREMENT COMMENT 'auto increment field',
  `Last_Name` VARCHAR(45) NULL COMMENT 'surname of borrower',
  `First_Name` VARCHAR(45) NULL COMMENT 'first name of borrower',
  `Borrower_email` VARCHAR(45) NULL COMMENT 'email of borrower',
  PRIMARY KEY (`Borrower_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Book_Loan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Book_Loan` ;

CREATE TABLE IF NOT EXISTS `Book_Loan` (
  `Book_BookID` INT NOT NULL,
  `Borrower_Borrower_ID` INT NOT NULL,
  `Comment` VARCHAR(45) NULL,
  `Date_out` DATE NULL DEFAULT NULL COMMENT 'Date when book was loaned out.',
  `Date_returned` DATE NULL DEFAULT NULL COMMENT 'Date when book was returned.',
  CONSTRAINT `fk_Book_Loan_Book1`
    FOREIGN KEY (`Book_BookID`)
    REFERENCES `Book` (`BookID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Book_Loan_Borrower1`
    FOREIGN KEY (`Borrower_Borrower_ID`)
    REFERENCES `Borrower` (`Borrower_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Book_Loan_Book1_idx` ON `Book_Loan` (`Book_BookID` ASC);

CREATE INDEX `fk_Book_Loan_Borrower1_idx` ON `Book_Loan` (`Borrower_Borrower_ID` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
